version: '3.10'

services:
  db:
    image: postgres:12
    # environment

    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "443:443"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=docker
    depends_on:
      - db

volumes:
  postgres_data:
